function appendMvaHtml(){

var mva_html = [
'                      <div id="fault" class="question mva" style="display:none;">',
'                          <h1> Who Was Found At Fault For The Accident?</h1>',
'                          <button type="button" class="btn btn-primary button2 Continue" data-answer="OtherDriver" data-value="fault">The Other Driver</button>',
'                          <button type="button" class="btn btn-primary button2 Continue" data-answer="Me" data-value="fault">Me</button>',
'                      </div>',
'                      <div id="divRequiredHospital" class="question mva" style="display:none;">',
'                          <h1> Did You Go To The Hospital?</h1>',
'                          <button type="button" class="btn btn-primary button2 Continue override special noFill" data-answer="yes" data-value="required_hospital">Yes</button>',
'                          <button type="button" class="btn btn-primary  button2 Continue special noFill" data-answer="no" data-value="required_hospital">No</button>',
'                      </div><!--Endquestion10 -->',
'                      <div id="question12" class="question mva" style="display:none;">',
'                          <h1> Did You Get Medical Treatment Other Than At A Hospital?</h1>',
'                          <button type="button" class="btn btn-primary button2 Continue special noFill" data-answer="yes" data-value="Other_treatment">Yes</button>',
'                          <button type="button" class="btn btn-primary  button2 Continue special noFill" data-answer="no" data-value="Other_treatment">No</button>',
'                      </div><!--Endquestion12 -->',
'                      <div id="attorneyDiv" class="question mva" style="display:none;">',
'                          <h1>Do you already have<br> a lawyer for this case?</h1>',
'                          <br>',
'                          <button type="button" class="btn btn-primary button2 Continue override" data-answer="no" data-value="attorney">No</button>',
'                          <button type="button" class="btn btn-primary  button2 Continue " data-answer="yes" data-value="attorney">Yes</button><br><br>',
'                      </div><!--Endquestion12 -->',
                        '<div id="div_attorney_dropdown" class="question list-group text-center mainFlow pi" style="display:none">	',
'                              <h2 class=text-center>If You Already Have An Attorney For This Claim, Why Are You Filling Out This Form?</h2>		',
'                              <a type="" class="list-group-item Continue special override" data-answer="A" data-value="attorney_dropdown" ><h4>I just have an attorney that I go to with all legal matters, but not for this claim <i class="glyphicon glyphicon-chevron-right pull-right green"></i></h4></a>',
'                              <a type="" class="list-group-item Continue special override" data-answer="B" data-value="attorney_dropdown" ><h4>I have a pre-paid attorney, but not for this claim<i class="glyphicon glyphicon-chevron-right pull-right green"></i></h4></a>',
'                              <a type="" class="list-group-item Continue special override" data-answer="C" data-value="attorney_dropdown" ><h4>I’ve spoken to an attorney but I haven’t signed a retainer to pursue this claim<i class="glyphicon glyphicon-chevron-right pull-right green"></i></h4></a>',
'                              <a type="" class="list-group-item Continue special override" data-answer="D" data-value="attorney_dropdown" ><h4>I’m looking for a second opinion before I hire an attorney<i class="glyphicon glyphicon-chevron-right pull-right green"></i></h4></a>',
'                              <a type="" class="list-group-item Continue special override" data-answer="E" data-value="attorney_dropdown" ><h4>I probably can\'t afford an attorney<i class="glyphicon glyphicon-chevron-right pull-right green"></i></h4></a>',
'                              <a type="" class="list-group-item Continue special override" data-answer="F" data-value="attorney_dropdown" ><h4>I’ve spoken to an attorney and they said I didn’t have a case<i class="glyphicon glyphicon-chevron-right pull-right red"></i></h4></a>',
'                              <a type="" class="list-group-item Continue special override" data-answer="G" data-value="attorney_dropdown" ><h4>I already settled my claim and want to see if I can get more<i class="glyphicon glyphicon-chevron-right pull-right red"></i></h4></a>',
'                              <a type="" class="list-group-item Continue special override" data-answer="H" data-value="attorney_dropdown" ><h4>I\'m unhappy with my current attorney<i class="glyphicon glyphicon-chevron-right pull-right red"></i></h4></a>',
'                              <a type="" class="list-group-item Continue special" data-answer="I" data-value="attorney_dropdown" ><h4>Other:<i class="glyphicon glyphicon-chevron-right pull-right red"></i></h4></a>',
'                          <br>',
'                          <div id="attorney_other_div" class="text-center" style="display:none;">',
'                              <label>Please Explain:</label>',
'                              <textarea class="form-control confirmation" rows="4"  type="text" placeholder="Type the story of how your accident happened here..." id="attorney_other" name="attorney_other"></textarea><br>',
'                          </div>',
'                          <button type="button" class="btn btn-primary button2 Continue special" data-value="attorney_dropdown" >Continue</button>',
'                      </div>',
'                      <div id="question27" class="question mva" style="display:none;">',
'                          <div class="form-inline">',
'                              <h1><label>What Was Month And Year Of the Accident?</label></h1><br>',
'                              <div class="form-group">',
'                                  <label class="sr-only">Month</label>',
'                                  <select name="month" class="form-control input-lg inputWidth center">',
'                                      <option>January</option>',
'                                      <option>February</option>',
'                                      <option>March</option>',
'                                      <option>April</option>',
'                                      <option>May</option>',
'                                      <option>June</option>',
'                                      <option>July</option>',
'                                      <option>August</option>',
'                                      <option>September</option>',
'                                      <option>October</option>',
'                                      <option>November</option>',
'                                      <option>December</option>',
'                                  </select>',
'                              </div>',
'                              <div class="form-group">',
'                                  <label class="sr-only" >Year</label>',
'                                  <select name="year" id="year" class="form-control input-lg inputWidth center year">',
'                                      <option>2015</option>',
'                                      <option>2014</option>',
'                                      <option>2013</option>',
'                                      <option value="2011">2012 Or Before</option>',
'                                  </select>',
'                              </div>',
'                          </div><br>',
'                          <button type="button" class="btn btn-primary button2 Continue" data-answer="complete" data-value="month_year" >Continue</button>',
'                      </div>',
'                      <div id="question29" class="question mva" style="display:none;">',
'                          <h1>Zip Code Of Accident</h1><br>',
'                          <input type="tel" name="zip_code" id="zip_code" class="form-control input-lg inputWidth center" onKeyPress="return disableEnterKey(event)" placeholder="Click Here, Type Your Zip">',
'                          <br>',
'                          <button type="button" class="btn btn-primary button2 Continue validate special" data-answer="complete" data-value="zip_code">Continue</button><!-- continueImage -->',
'                      </div> ',
'                      <div id="question20" class="question mva" style="display:none;">',
'                          <h1>Where Did The Accident Happen?</h1><br>',
'                          City<br>',
'                          <input type="text" name="accident_city" class="form-control input-lg inputWidth center cityState" onKeyPress="return disableEnterKey(event)" id="accident_city" placeholder="City">',
'                          State (ie UT)<br>',
'                          <input type="text" name="accident_state" maxlength="2" id="accident_state" onKeyPress="return disableEnterKey(event)" class="form-control twochar input-lg inputWidth center cityState" placeholder="State">',
'                          <button type="button" class="btn btn-primary button2 Continue validate noFill"  data-answer="complete" data-value="city_state_of_accident" >Confirm</button>',
'                          <button type="button" class="btn btn-primary button2 Continue validate noFill"  data-answer="complete" data-value="city_state_of_accident" >Change</button>',
'                      </div>',
'                      <div id="divInjured" class="question mva" style="display:none;">   ',
'                          <h1>Did The Damages In the Accident Happen To You Or A Loved One?</h1>',
'                          <button type="button" class="btn btn-primary button2 Continue override" data-answer="me" data-value="damagesHappenTo">Me</button>',
'                          <button type="button" class="btn btn-primary  button2 Continue" data-answer="loved_one" data-value="damagesHappenTo">Loved One</button>',
'                      </div>',
'                      <div id="divNameOfInured" class="question mva"  style="display:none;">',
'                          <h1>Type The Name Of The Injured Person?</h1>',
'                          <div class="form-group">',
'                              <input type="text" name="name_of_injured" class="form-control input-lg inputWidth center name_of_injured confirmation" onKeyPress="return disableEnterKey(event)" id="name_of_injured" placeholder="Click Here,Type The Name">',
'                              <button type="button" class="btn btn-primary button2 Continue validate" data-answer="nameOfInjured" data-value="name_of_injured">Continue</button>',
'                          </div>',
'                      </div>',
'                      <div id="question27" class="question mva" style="display:none;">',
'                          <div class="form-inline">',
'                              <h1><label>What Is Your Name?</label></h1><br>',
'                              <div class="form-group">',
'                                  <label class="sr-only">First</label>',
'                                  <input type="text" class="form-control input-lg inputWidth center name confirmation special" id="first_name" name="first_name" onKeyPress="return disableEnterKey(event)" placeholder="First Name">',
'                              </div>',
'                              <div class="form-group">',
'                                  <label class="sr-only" >Last</label>',
'                                  <input type="text" class="form-control input-lg inputWidth center name confirmation" id="last_name" name="last_name" onKeyPress="return disableEnterKey(event)"  placeholder="Last Name">',
'                              </div>',
'                          </div><br>',
'                          <button type="button" class="btn btn-primary button2 Continue validate" data-answer="complete" data-value="name" >Continue</button><!--continueName -->',
'                      </div>',
'                      <div id="divEmail" class="question mva " style="display:none;">',
'                          <h1>Type Your Best Email:</h1><br>',
'                          <div class="form-group">',
'                              <label class="sr-only" for="exampleInputEmail2">Email address</label>',
'                              <input type="email" class="form-control input-lg inputWidth center confirmation" name="email_address" id="email_address" onKeyPress="return disableEnterKey(event)" placeholder="Click Here, Type Your Email">',
'                          </div>',
'                          <button type="button" class="btn btn-primary button2 Continue validate" data-answer="complete" data-value="email">Continue</button>',
'                      </div>',
'                      <div id="divAddress" class="question mva" style="display:none;">',
'                          <h1>Type Your Address:</h1><br>',
'                          Street Address<br>',
'                          <input type="text" name="address" id="address" class="form-control input-lg inputWidth center" placeholder="Street Address">',
'                          City<br>',
'                          <input type="text" name="city" class="form-control input-lg inputWidth center" onKeyPress="return disableEnterKey(event)" id="city" placeholder="City">',
'                          State (ie UT)<br>',
'                          <input type="text" name="state" maxlength="2" id="state" onKeyPress="return disableEnterKey(event)" class="form-control twochar input-lg inputWidth center" placeholder="State">',
'                          <button type="button" class="btn btn-primary  button2 Continue validate" data-answer="complete" data-value="address"  >Continue</button>  ',
'                      </div>',
'                      <div id="divCaseNotes" class="question mva" style="display:none;">',
'                          <h1><label>Type The Story Of How You Were Injured Here:</label></h1>',
'                          <div class="form-group">',
'                              <textarea class="form-control confirmation" rows="4" id="case_notes" name="case_notes" onKeyPress="return disableEnterKey(event)" placeholder="Type the story of how your accident happened here..."></textarea>',
'                          </div><br>',
'                          <button type="button" class="btn btn-primary button2 Continue validate" data-answer="complete" data-value="case_notes" >Continue</button><!--continueName -->',
'                      </div>',
'                      <div id="divContact2" class="question list-group mainFlow mva" style="display:none">',
'                          <div id="confirmation"></div>',
'                          <div class="form-group">',
'                              <h2 class="confirmationHide">How Can We Reach You?</h2><br>',
'                              <input type="tel" class="form-control input-lg inputWidth center confirmation"  name="phone_home" id="phone_home" placeholder="Click Here, Type Phone Number"><br>',
'                          </div>',
'                          <input id="formSubmit" type="button" class="btn3 btn-success button2 Continue validate submit" data-value="formSubmit" value="Yes! I Want My Free Claim Review"/>',
'                          <br>',
'                          <br><br>',
'                          <div id="disclosure"> ',
'                              <small>By clicking the "Submit" button below, you agree that law firms you are matched with may contact you by telephone even if you are on a federal or state Do Not Call registry. Up to 10 law firms may respond to your request within approximately 2 weeks. In some cases 3 or more firms may respond to your request after 30 days. You may also be contacted by a third-party lead verification service to confirm the accuracy or completeness of the information you submit.</small>',
'                          </div>',
'                      </div>',
''
].join('');


$("#question2").after(mva_html);

}


